Repository arnab2001/Coinverse, pull requests merged in 2023-02, with the labels that each got.

#16 Fixed all typos and improved README.md and added some documentation
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE.md
  README.md
Labels: jwoc, Easy

#28 My new branch 2
  package-lock.json
  package.json
  public/index.html
  src/App.css
Labels: jwoc, Medium

#34 new pr for the issue i raised
  src/App.css
Labels: jwoc, Medium

#37 My new branch 5
  src/App.css
  src/App.js
  src/components/Homepage.jsx
  src/components/Navbar.jsx
  src/components/nav.css
Labels: ui, jwoc, hard

#39 Closes #8 [Cypress Test Suite]
  cypress.config.js
  cypress/e2e/spec.cy.js
  cypress/fixtures/example.json
  cypress/support/commands.js
  cypress/support/e2e.js
  package-lock.json
  package.json
Labels: testing, jwoc, Medium

#44 uploaded coinverse logo png
  src/images/coinverse-logo.png
Labels: jwoc, Easy
