Repository arnab2001/Coinverse, pull requests merged in 2023-03, with the labels that each got.

#46 improved footer design
  src/components/Navbar.jsx
  src/components/nav.css
  src/images/icons8-facebook-50 (1).png
  src/images/icons8-github-50.png
  src/images/icons8-instagram-50.png
  src/images/icons8-linkedin-circled-50.png
  src/images/icons8-twitter-50.png
Labels: jwoc, Medium

#47 Added new News API
  src/App.css
  src/components/BackupNews.jsx
  src/components/Homepage.jsx
  src/components/Navbar.jsx
  src/components/index.js
Labels: jwoc, hard

#53 footer design is done
  src/components/Navbar.jsx
  src/components/nav.css
  src/images/icons8-twitter-50.png
Labels: ui, Medium

#59 ISSUE #57
  package-lock.json
  src/components/Navbar.jsx
Labels: jwoc, Easy

#61 Sticky navbar and sidebar
  src/components/Homepage.jsx
  src/components/Navbar.jsx
  src/components/nav.css
Labels: jwoc, Medium

#70 content going out of screen bug fix 2nd pr
  src/App.css
  src/components/Navbar.jsx
  src/components/nav.css
Labels: jwoc, Medium

#71 responsive footer
  src/components/Navbar.jsx
  src/components/nav.css
Labels: jwoc, Medium

#63 [#22][#62] card-bookmarks/screen-size
  src/App.css
  src/components/Bookmarks.jsx
  src/components/CryptoDetailes.jsx
  src/components/Cryptocurrencies.jsx
  src/components/Homepage.jsx
  src/components/Navbar.jsx
  src/components/News.jsx
  src/components/nav.css
Labels: enhancement, ui

#77 cypto stats cards 2nd pr
  src/App.css
  src/components/Homepage.jsx
  src/components/Navbar.jsx
Labels: jwoc, Medium

#88 Badges added
  README.md
Labels: jwoc, Easy

#90 ui enhancement of crypto details page (titles hover animations)
  src/App.css
  src/components/CryptoDetailes.jsx
  src/components/LineChart.jsx
  src/components/Navbar.jsx
Labels: jwoc, Medium

#92 applied swiper ( swiper.js used ) to global crypto stats cards( for now its unresponsive )
  package-lock.json
  package.json
  src/App.css
  src/components/Homepage.jsx
Labels: jwoc, Medium

#93 Added more cypress testing cases
  cypress/e2e/spec.cy.js
Labels: testing, jwoc, Medium

#98 Added scroll back to top button in every page
  package-lock.json
  package.json
  src/App.css
  src/components/CryptoDetailes.jsx
  src/components/Cryptocurrencies.jsx
  src/components/Homepage.jsx
  src/components/News.jsx
Labels: ui, jwoc, Medium

#105 Added About Us Component
  src/App.js
  src/components/AboutUs.jsx
  src/components/Navbar.jsx
  src/components/about.css
  src/components/index.js
Labels: jwoc, Medium
